In [1]:
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
print('a')
import string

a


In [2]:
email =pd.read_csv('C:/Users/admin/Downloads/archive (15)/spam_ham_dataset.csv')

In [3]:
email


text  spam
0     Subject: enron methanol ; meter # : 988291\r\n...     0
1     Subject: hpl nom for january 9 , 2001\r\n( see...     0
2     Subject: neon retreat\r\nho ho ho , we ' re ar...     0
3     Subject: photoshop , windows , office . cheap ...     1
4     Subject: re : indian springs\r\nthis deal is t...     0
...                                                 ...   ...
5166  Subject: put the 10 on the ft\r\nthe transport...     0
5167  Subject: 3 / 4 / 2000 and following noms\r\nhp...     0
5168  Subject: calpine daily gas nomination\r\n>\r\n...     0
5169  Subject: industrial worksheets for august 2000...     0
5170  Subject: important online banking alert\r\ndea...     1

[5171 rows x 2 columns]

In [4]:
email.shape

(5171, 2)

In [5]:
email.columns

Index(['text', 'spam'], dtype='object')

In [6]:
email.drop_duplicates(inplace = True)

In [7]:
email.shape


(4993, 2)

In [8]:
#show the no of missing data
email.isnull().sum()

text    0
spam    0
dtype: int64

In [10]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [11]:
def process_text(text):
    nopunc =[char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    
    clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    
    return clean_words

In [12]:
# show the tokenize (a list of tokens also called as lemmas)
email['text'].head().apply(process_text)

0    [Subject, enron, methanol, meter, 988291, foll...
1    [Subject, hpl, nom, january, 9, 2001, see, att...
2    [Subject, neon, retreat, ho, ho, ho, around, w...
3    [Subject, photoshop, windows, office, cheap, m...
4    [Subject, indian, springs, deal, book, teco, p...
Name: text, dtype: object

In [14]:
message4 = 'hello hello hello world play'
message5 = 'test test test test one hello'
print(message4)
print()

# convert the text in matrix
from sklearn.feature_extraction.text import CountVectorizer
bow4 = CountVectorizer(analyzer = process_text).fit_transform([[message4],[message5]])
print(bow4)

hello hello hello world play

  (0, 0)	3
  (0, 4)	1
  (0, 2)	1
  (1, 0)	1
  (1, 3)	4
  (1, 1)	1


In [15]:
bow4.shape

(2, 5)

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
messages = CountVectorizer(analyzer=process_text).fit_transform(email['text'])
print(messages)

  (0, 4725)	1
  (0, 18720)	1
  (0, 31024)	1
  (0, 31017)	1
  (0, 4649)	1
  (0, 20852)	1
  (0, 33195)	1
  (0, 21764)	1
  (0, 31711)	1
  (0, 2170)	1
  (0, 1665)	1
  (0, 11)	1
  (0, 36658)	1
  (0, 20741)	1
  (0, 15292)	1
  (0, 37205)	1
  (0, 15235)	1
  (0, 36028)	1
  (0, 34458)	1
  (0, 36288)	1
  (0, 15137)	2
  (0, 47829)	1
  (0, 36724)	1
  (0, 50110)	1
  (0, 38632)	1
  :	:
  (4992, 13620)	1
  (4992, 47161)	1
  (4992, 38564)	1
  (4992, 46786)	1
  (4992, 38480)	4
  (4992, 24458)	1
  (4992, 25893)	1
  (4992, 19862)	1
  (4992, 13260)	1
  (4992, 20444)	1
  (4992, 48158)	1
  (4992, 13896)	1
  (4992, 30857)	1
  (4992, 26420)	1
  (4992, 43882)	1
  (4992, 40265)	1
  (4992, 13301)	2
  (4992, 13500)	1
  (4992, 25012)	1
  (4992, 38932)	1
  (4992, 21156)	1
  (4992, 25957)	1
  (4992, 12516)	3
  (4992, 26074)	1
  (4992, 11992)	1


In [36]:
messages.shape

(4993, 50381)

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
x_train,x_test,y_train,y_test = train_test_split(messages,email['spam'],test_size =0.20,random_state = 0)

In [39]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(x_train,y_train)
print(classifier.predict(x_train))

[1 0 1 ... 0 0 1]


In [40]:
from sklearn.metrics import classification_report ,confusion_matrix,accuracy_score
pred = classifier.predict(x_train)
print(classification_report(y_train,pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99      2809
           1       0.98      0.99      0.99      1185

    accuracy                           0.99      3994
   macro avg       0.99      0.99      0.99      3994
weighted avg       0.99      0.99      0.99      3994



In [41]:
print('confusion matrix \n',confusion_matrix(y_train,pred))

confusion matrix 
 [[2787   22]
 [  13 1172]]


In [42]:
print('accuracy',accuracy_score(y_train,pred))

accuracy 0.9912368552829244


In [44]:
print(classifier.predict(x_test))
print(y_test.values)

[0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 0 1 0 1 1 1 0 1 1
 0 0 0 0 1 0 1 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 1 1 0 0 1 1 1 0
 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 0 0 1 0
 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0 1 1 0 0 1 0 0 1 0 1 1 0 1 0 1 0 0
 0 0 1 0 1 0 1 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 1 1 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0
 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1
 0 0 0 0 0 1 1 0 0 1 1 1 0 1 0 0 0 0 0 0 0 1 0 1 1 0 1 1 1 0 0 0 1 0 1 0 0
 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 1 0 1
 0 0 1 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 

In [45]:
from sklearn.metrics import classification_report ,confusion_matrix,accuracy_score
pred = classifier.predict(x_test)
print(classification_report(y_test,pred))
print('confusion matrix \n',confusion_matrix(y_test,pred))
print('accuracy',accuracy_score(y_test,pred))


              precision    recall  f1-score   support

           0       0.98      0.98      0.98       722
           1       0.95      0.96      0.96       277

    accuracy                           0.98       999
   macro avg       0.97      0.97      0.97       999
weighted avg       0.98      0.98      0.98       999

confusion matrix 
 [[709  13]
 [ 11 266]]
accuracy 0.975975975975976
